buycoffee/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('creator.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
]

creator/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

app_name = 'creator'

urlpatterns = [
    path('mypage/', views.mypage, name='mypage'),
    path('creators/', views.creators, name='creators'),
    path('creators/<int:pk>/', views.creator, name='creator'),
    path('signup/', views.signup, name='signup'), 
    path('login/', auth_views.LoginView.as_view(template_name='creator/login.html'), name='login'),
    path('logout/', views.logout, name='logout'),
    path('edit/', views.edit, name='edit'),    
]

core/models.py
from django.db import models

# Create your models here.

creator/models.py
from django.db import models
from django.contrib.auth.models import User


class Creator(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to='uploads/creators')
    user = models.OneToOneField(User, related_name='creator', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

creator/forms.py
from django.forms import ModelForm
from .models import Creator


class CreatorForm(ModelForm):
    class Meta:
        model = Creator
        fields = ('title', 'description', 'image',)

core/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'core/index.html')

creator/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Creator
from .forms import CreatorForm


@login_required
def mypage(request):
    creator = request.user.creator
    context = {'creator': creator}
    return render(request, 'creator/mypage.html', context)


def signup(request):       
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'You are successfully signed up. Please continue to log in...')
            return redirect('creator:login')
        else:
            form = UserCreationForm()
            messages.success(request, 'Something wrong with the signup. Please try again...')
            return render(request, 'creator/signup.html', {'form': form})
    else:
        form = UserCreationForm()
        return render(request, 'creator/signup.html', {'form': form})


@login_required
def logout(request):
    auth.logout(request)
    messages.success(request, 'You are successfully logged out...')    
    return redirect('creator:login')


def creators(request):
    # Get creators
    creators = Creator.objects.all()
    context = {'creators': creators}
    return render(request, 'creator/creators.html', context)


def creator(request, pk):
    creator = Creator.objects.get(pk=pk)
    context = {'creator': creator}
    return render(request, 'creator/creator.html', context)


def edit(request):
    try:
        creator = request.user.creator
        if request.method == 'POST':
            form = CreatorForm(request.POST, request.FILES, instance=creator)
            if form.is_valid():
                form.save()
                return redirect('core:index')
        else:
            form = CreatorForm(instance=creator)
    except Exception:
        if request.method == 'POST':
            form = CreatorForm(request.POST, request.FILES)
            if form.is_valid():
                creator = form.save(commit=False)
                creator.user = request.user
                creator.save()
                return redirect('core:index')
        else:
            form = CreatorForm()
    return render(request, 'creator/edit.html', {'form': form})

core/templates/core/base.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <script src="https://cdn.tailwindcss.com"></script>
        <title>{% block title %}{% endblock %} | Buy Me a Coffee</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body class="bg-slate-700">
        <nav class="py-8 px-8 flex flex-row items-center justify-between bg-slate-900">
            <div>
                <a href="{% url 'core:index' %}" class="text-2xl text-white font-bold">Buy Me a Coffee</a>
            </div>
            <div class="space-x-6">
                <a href="{% url 'creator:creators'%}" class="py-4 px-6 text-lg font-bold text-white">Creators</a>
                {% if not request.user.is_authenticated %}
                    <a href="{% url 'creator:login' %}" class="py-4 px-6 text-lg font-bold text-white">
                        Log in
                    </a>
                    <a href="{% url 'creator:signup' %}" class="py-4 px-6 text-lg font-bold text-white bg-sky-800 rounded-lg">
                        Sign up
                    </a>
                {% else %}                    
                    <a href="{% url 'creator:logout' %}" class="py-4 px-6 text-lg font-bold text-white">
                        Log out
                    </a>
                    <a href="{% url 'creator:mypage' %}" class="py-4 px-6 text-lg font-bold text-white bg-sky-800 rounded-lg">
                        My page
                    </a>
                    <a class="py-4 px-6 text-lg font-bold text-amber-300">
                        Hi, {{ request.user.username }}
                    </a>
                {% endif %}               
            </div>
        </nav>

        {% if messages %}
            {% for message in messages %}                         
                <div class="p-4 mb-4 text-sm text-blue-800 rounded-lg bg-blue-100 dark:bg-gray-800 dark:text-blue-400" role="alert">
                    {{ message }}
                </div>                               
            {% endfor %}                
        {% endif %}

        <main class="py-6 px-8">
            {% block content %}
            {% endblock content %}
        </main>

        <footer class="py-6 px-8 text-center bg-slate-600">
            <p class="text-slate-200">Copyright (c) 2024 - Buy Me a Coffee</p>
        </footer>

        {% block scripts %}
        {% endblock scripts %}
    </body>
</html>

core/templates/core/index.html
{% extends "core/base.html" %}
{% load static %}

{% block title %}Welcome{% endblock title %}

{% block content %}
    <div class="py-20 text-center space-y-12">
        <h1 class="text-7xl text-slate-300 font-bold">Get paid for your work</h1>
        <p class="text-xl text-slate-400">
            This is just some random information to show how it would look like with some actual content.
        </p>
        <a href="#" class="py-8 px-12 inline-block text-xl text-white bg-sky-800 rounded-lg">Create page</a>
    </div>
    <div class="py-12 bg-slate-800">
        <h2 class="mb-12 text-5xl text-slate-300 text-center font-bold">
            Newest creators
        </h2>
        <div class="px-12 grid grid-cols-4 gap-8">
            <div class="bg-slate-600 rounded-lg">
                <div class="py-6 px-8 space-y-6">
                    <figure>
                        <img src="{% static 'images/profile_pic_1.jpg' %}" class="rounded-tr-lg rounded-tl-lg">
                    </figure>
                    <div class="py-6 px-8 space-y-6">
                        <h3 class="text-xl text-slate-200 font-bold">John Dog</h3>    
                        <p class="text-slate-300">
                            This is just some random information to show how it would look like with some actual content.
                        </p>    
                        <a href="#" class="py-4 px-6 inline-block text-xl text-white bg-sky-800 rounded-xl">Read more</a>
                    </div>
                </div>
            </div>
            <div class="bg-slate-600 rounded-lg">
                <div class="py-6 px-8 space-y-6">
                    <figure>
                        <img src="{% static 'images/profile_pic_1.jpg' %}" class="rounded-tr-lg rounded-tl-lg">
                    </figure>
                    <div class="py-6 px-8 space-y-6">
                        <h3 class="text-xl text-slate-200 font-bold">John Dog</h3>    
                        <p class="text-slate-300">
                            This is just some random information to show how it would look like with some actual content.
                        </p>    
                        <a href="#" class="py-4 px-6 inline-block text-xl text-white bg-sky-800 rounded-xl">Read more</a>
                    </div>
                </div>
            </div>
            <div class="bg-slate-600 rounded-lg">
                <div class="py-6 px-8 space-y-6">
                    <figure>
                        <img src="{% static 'images/profile_pic_1.jpg' %}" class="rounded-tr-lg rounded-tl-lg">
                    </figure>
                    <div class="py-6 px-8 space-y-6">
                        <h3 class="text-xl text-slate-200 font-bold">John Dog</h3>    
                        <p class="text-slate-300">
                            This is just some random information to show how it would look like with some actual content.
                        </p>    
                        <a href="#" class="py-4 px-6 inline-block text-xl text-white bg-sky-800 rounded-xl">Read more</a>
                    </div>
                </div>
            </div>
            <div class="bg-slate-600 rounded-lg">
                <div class="py-6 px-8 space-y-6">
                    <figure>
                        <img src="{% static 'images/profile_pic_1.jpg' %}" class="rounded-tr-lg rounded-tl-lg">
                    </figure>
                    <div class="py-6 px-8 space-y-6">
                        <h3 class="text-xl text-slate-200 font-bold">John Dog</h3>    
                        <p class="text-slate-300">
                            This is just some random information to show how it would look like with some actual content.
                        </p>    
                        <a href="#" class="py-4 px-6 inline-block text-xl text-white bg-sky-800 rounded-xl">Read more</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

creator/templates/creator/creator.html
{% extends 'core/base.html' %}

{% block title %}{{ creator.title }}{% endblock %}

{% block content %}
    <div class="py-20 grid grid-cols-3 items-center">
        <figure class="col-span-1">
            <img src="{{ creator.image.url }}" class="rounded-lg">
        </figure>
        <div class="col=span-2 space-y-12 text-center">
            <h1 class="text-7xl text-slate-300 font-bold">{{ creator.title }}</h1>
            <p class="text-xl text-slate-400">
                {{ creator.description }}
            </p>
        </div>
        
    </div>
    <div class="py-12 bg-slate-800">    
        <div class="px-12">
            <h2 class="mb-12 text-5xl text-slate-300 text-center font-bold">Supprt me</h2>
            <p class="text-xl text-slate-400 text-center">
                Lorem Ipsum is simply dummy text of the printing and typesetting industry.
            </p>
            <div class="mt-12 flex flex-row space-x-4 items-center justify-center">
                <a href="#" class="py-4 px-6 inline-block text-xl text-white bg-sky-800 rounded-lg">
                    Buy me "1" coffee $1
                </a>
                <a href="#" class="py-4 px-6 inline-block text-xl text-white bg-sky-800 rounded-lg">
                    Buy me "2" coffee $2
                <a href="#" class="py-4 px-6 inline-block text-xl text-white bg-sky-800 rounded-lg">
                    Buy me "5" coffee $5
                </a>
            </div>
        </div>       
    </div>
{% endblock %}

creator/templates/creator/creators.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Creators{% endblock %}

{% block content %}
    <div class="py-20 text-center space-y-12">
        <h1 class="text-7xl text-slate-300 font-bold">Creators</h1>
    </div>

    <div class="py-12 bg-slate-800">    
        <div class="px-12 grid grid-cols-4 gap-8">
            {% for creator in creators %}
                <div class="bg-slate-600 rounded-lg">
                    <div class="py-6 px-8 space-y-6">
                        <figure>
                            <img src="{{ creator.image.url }}" class="rounded-tr-lg rounded-tl-lg">
                        </figure>
                        <div class="py-6 px-8 space-y-6">
                            <h3 class="text-xl text-slate-200 font-bold">{{ creator.title }}</h3>    
                            <p class="text-slate-300">
                                {{ creator.description }}
                            </p>    
                            <a href="{% url 'creator:creator' creator.id %}" class="py-4 px-6 inline-block text-xl text-white bg-sky-800 rounded-xl">
                                Read more
                            </a>
                        </div>
                    </div>
                </div>
            {% endfor %}            
        </div>
    </div>
{% endblock %}

creator/templates/creator/edit.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}Edit{% endblock %}

{% block content %}
    <div class="py-20 text-center space-y-12">
        <h1 class="text-7xl text-slate-300 font-bold">Edit</h1>
    </div>
    <div class="py-12 bg-slate-800 text-blue-500">
        <form method="post" action="." enctype="multipart/form-data">
            {% csrf_token %}        
            {{ form|crispy }}
            <div>
                <button class="w-full py-6 px-8 bg-sky-800 text-white font-bold rounded-lg">Submit</button>
            </div>
        </form>
    </div>
{% endblock %}

creator/templates/creator/login.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}Log in {% endblock %}

{% block content %}
    <div class="py-20 text-center">
        <h1 class="text-7xl text-slate-300 font-bold">Log in</h1>
    </div>
    <div class="max-w-lg mx-auto px-8 py-12 bg-slate-800">
        <form method="post" action="." class="space-y-6">
            {% csrf_token %}        
            <div class="space-y-4">
                <label for="id_username" class="text-lg text-white">Username:</label>
                <input type="text" class="w-full py-6 px-8 bg-slate-600 text-white font-bold rounded-lg" name="username" autofocus="" autocapitalize="none" autocomplete="username" maxlength="150" required="" id="id_username">
            </div>
            <div class="space-y-4">
                <label for="id_password" class="text-lg text-white">Password:</label>
                <input type="password" class="w-full py-6 px-8 bg-slate-600 text-white font-bold rounded-lg" name="password" autocomplete="current-password" required="" id="id_password">
            </div>
            {% if form.errors %}
                <div class="py-6 px-8 bg-amber-600 text-white rounded-lg">
                    <p>Username or password is not correct!</p>
                </div>
            {% endif %}
            <div>
                <button class="w-full py-6 px-8 bg-sky-800 text-white font-bold rounded-lg">Submit</button>
            </div>
        </form>
    </div>
{% endblock %}

creator/templates/creator/mypage.html
{% extends 'core/base.html' %}

{% block title %}{{ creator.title }}{% endblock %}

{% block content %}
    <div class="py-20 grid grid-cols-3 items-center">
        <figure class="col-span-1">
            <img src="{{ creator.image.url }}" class="rounded-lg">
        </figure>
        <div class="col=span-2 space-y-12 text-center">
            <h1 class="text-7xl text-slate-300 font-bold">{{ creator.title }}</h1>
            <p class="text-xl text-slate-400">
                {{ creator.description }}
            </p>
        </div>
        
    </div>
    <div class="py-12 bg-slate-800">    
        <div class="px-12">
            <h2 class="mb-12 text-5xl text-slate-300 text-center font-bold">My supporters</h2>
            <p class="text-xl text-slate-400 text-center">
                Lorem Ipsum is simply dummy text of the printing and typesetting industry.
            </p>
            <div class="mt-12 text-center text-white space-y-5">
                <p class="text-xl">john@doe.com - One coffee = $1(April 12, 2024)</p>
                <br>
                <p class="text-xl font-bold">Total: $1</p>
            </div>
        </div>       
    </div>
{% endblock %}

creator/templates/creator/signup.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Sign up{% endblock %}

{% block content %}
    <div class="py-20 text-center">
        <h1 class="text-7xl text-slate-300 font-bold">Sign up</h1>
    </div>

    <div class="max-w-lg mx-auto px-8 py-12 bg-slate-800">
        <form method="post" action="." class="space-y-6">
            {% csrf_token %}            
            <div class="space-y-4">
                <label for="id_username" class="text-lg text-white">Username:</label>
                <input type="text" class="w-full py-6 px-8 bg-slate-600 text-white font-bold rounded-lg" name="username" autofocus="" autocapitalize="none" autocomplete="username" maxlength="150" required="" id="id_username">
            </div>
            <div class="space-y-4">
                <label for="id_password1" class="text-lg text-white">Password:</label>
                <input type="password" class="w-full py-6 px-8 bg-slate-600 text-white font-bold rounded-lg" name="password1" autocomplete="current-password" required="" id="id_password1">
            </div>
            <div class="space-y-4">
                <label for="id_password2" class="text-lg text-white">Repeat password:</label>
                <input type="password" class="w-full py-6 px-8 bg-slate-600 text-white font-bold rounded-lg" name="password2" autocomplete="current-password" required="" id="id_password2">
            </div>
            {% if form.errors %}
                <div class="py-6 px-8 bg-amber-600 text-white rounded-lg">
                    <p>The username is already taken or there is something wrong with your passwords...</p>
                </div>
            {% endif %}
            <div>
                <button class="w-full py-6 px-8 bg-sky-800 text-white font-bold rounded-lg">Submit</button>
            </div>
        </form>
    </div>
{% endblock %}